package:
  name: oslo.config
  version: "2.2.0"

source:
  fn: oslo.config-2.2.0.tar.gz
  url: https://pypi.python.org/packages/source/o/oslo.config/oslo.config-2.2.0.tar.gz
  md5: 6e79afde0ec666162f585b707f9359d8
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # noarch_python: True
  # preserve_egg_dir: True
  entry_points:
    - oslo-config-generator = oslo_config.generator:main

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - pbr >=1.3

  run:
    - python
    - argparse # [py26]
    - netaddr >=0.7.12
    - six >=1.9.0
    - stevedore >=1.5.0

test:
  # Python imports
  imports:
    - oslo_config

  commands:
    - oslo-config-generator

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  #home: The package home page
  license: Apache Software License
  summary: 'Oslo Configuration API'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
